version: 2

builds:
  - main: ./cmd/cortex
    binary: cortex
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildDate={{.Date}}

brews:
  - repository:
      owner: Napageneral
      name: homebrew-tap
    homepage: https://github.com/Napageneral/cortex
    description: Cortex intelligence layer

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
